INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1000, 'Knock Bitzzz', 'Electric', 120, 15, 8004);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1001, 'Widgets', 'Non_Electric', 50, 35.5, 8004);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1002, 'Grommets', 'Non_Electric', 50, 23.45, 8001);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1003, 'Wedges', 'Non_Electric', 50, 10.15, 8020);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1004, 'Wing Bats', 'Non_Electric', 50, 11.25, 8003);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1005, 'Twinkies', 'Non_Electric', 75, 15.75, 8012);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1006, 'Wiggles', 'Non_Electric', 50, 12.34, 8020);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1007, 'Bing Bobs', 'Non_Electric', 50, 2.39, 8005);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1008, 'Wog Wits', 'Non_Electric', 300, 19.99, 8004);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1009, 'Barney Bits', 'Non_Electric', 50, 23.59, 8006);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1010, 'Willie Widgits', 'Non_Electric', 89, 12.99, 8003);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1011, 'Barge Bogs', 'Non_Electric', 50, 2.99, 8011);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1012, 'Poggy Pogs', 'Non_Electric', 99, 1.1, 8002);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1013, 'Pardle Pins', 'Non_Electric', 400, 0.69, 8013);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1014, 'Piddley Wicks', 'Non_Electric', 54, 5.19, 8013);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1015, 'Iggy Orks', 'Non_Electric', 50, 49.95, 8010);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1016, 'Crank Cribs', 'Non_Electric', 888, 0.29, 8005);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1017, 'Thingies', 'Non_Electric', 67, 45.98, 8008);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1018, 'Orf Dappers', 'Non_Electric', 50, 19.98, 8018);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1019, 'Piff Knocks', 'Non_Electric', 82, 4.95, 8002);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1020, 'Knit Piks', 'Non_Electric', 66, 6.75, 8015);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1021, 'Piddley Pins', 'Non_Electric', 370, 0.25, 8020);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1022, 'Tic Tocs', 'Non_Electric', 87, 1.36, 8014);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1023, 'Tin Wits', 'Non_Electric', 50, 5.67, 8014);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1024, 'Thinga-ma-bobs', 'Non_Electric', 40, 10.98, 8012);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1025, 'Fling Flobs', 'Non_Electric', 254, 2.33, 8009);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1026, 'Barn Bins', 'Non_Electric', 45, 88.67, 8006);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1027, 'Flap Wrappers', 'Non_Electric', 89, 44.88, 8009);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1028, 'Pong Pangs', 'Non_Electric', 2345, 0.1, 8002);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1029, 'Oof Tongs', 'Non_Electric', 345, 8.49, 8011);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1030, 'Nic Nacs', 'Non_Electric', 238, 2.99, 8015);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1031, 'Tork Tins', 'Non_Electric', 376, 0.95, 8012);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1032, 'Lilly Larks', 'Non_Electric', 56, 12.99, 8007);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1033, 'Minnie Morks', 'Non_Electric', 800, 1.95, 8007);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1034, 'Cork Handles', 'Non_Electric', 654, 2.66, 8016);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1035, 'Ding Darns', 'Non_Electric', 1208, 0.15, 8019);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1036, 'Erk Orks', 'Non_Electric', 498, 3.99, 8017);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1037, 'Foo Figs', 'Non_Electric', 234, 5.89, 8018);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1038, 'Googly Eyes', 'Non_Electric', 756, 6.99, 8001);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1039, 'Handy Pandies', 'Non_Electric', 298, 4.35, 8017);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1040, 'Inny Outies', 'Non_Electric', 219, 3.45, 8010);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1041, 'Cordless Drill', 'Electric', 40, 200, 8022);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1042, 'Circular Saw', 'Electric', 42, 300, 8022);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1094, 'Tester', 'Electric', 50, 150, 8022);
INSERT INTO ToolShop.TOOL (ToolID, Name, Type, Quantity, Price, SupplierID) VALUES (1095, 'Heavy Duty Blower', 'Electric', 49, 150, 8022);