INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8001,'Grommet Builders','788 30th St., SE, Calgary','Fred');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8002,'Pong Works','749 Dufferin Blvd., SE, Calgary','Bart');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8003,'Wiley Inc.','26 40th St., SE, Calgary','BillyBob');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8004,'Winork Manufacturing Inc.','156 51st Ave., SE, Calgary','Marty');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8005,'Grab Bag Inc.','138 42nd Ave., NE, Calgary','Monty');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8006,'Paddy''s Manufacturing','311 McCall Way, NE, Calgary','Barney');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8007,'Smickles Industries','966 Smed Lane, SE, Calgary','Lisa');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8008,'Thangs Inc.','879 37th Ave., NE, Calgary','Thelma');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8009,'Flip Works Inc.','472 Ogden Dale Rd., SE, Calgary','Rory');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8010,'Irkle Industries','754 Sunridge Way, NE, Calgary','Irma');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8011,'Biff Builders','690 19th St., NE, Calgary','Borjn');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8012,'Twinkles Inc.','318 29th St.,NE, Calgary','Barkley');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8013,'Piddles Industries','238 112th Ave., NE, Calgary','Parnell');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8014,'Tic Tac Manufacturing','598 Palmer Rd., NE, Calgary','Teisha');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8015,'Knock Knock Inc.','363 42nd Ave., NE, Calgary','Ned');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8016,'Corky Things Inc.','35 McCall Way, NE, Calgary','Corrine');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8017,'E & O Industries','883 44th St., SE, Calgary','Stan');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8018,'Fiddleys Makes Stuff Inc.','350 27th St., NE, Calgary','Fredda');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8019,'Horks and Stuff Manufacturing','997 42nd Ave., NE, Calgary','Harold');
INSERT INTO suppliers(id,company_name,address,sales_contact) VALUES (8020,'Wings Works','754 48th St., SE, Calgary','Wing');
